const produtos = [
    {
        id: "001",
        item: "Camiseta Rosa",
        price: 50.00,
        qtd: 5,
        imagem: "./img/produtos/blusa-rosa.png",
    },
    {
        id: "002",
        item: "Camiseta Preta",
        price: 50.00,
        qtd: 5,
        imagem: "./img/produtos/blusa-preta.png",
    },
    {
        id: "003",
        item: "Camiseta Verde",
        price: 50.00,
        qtd: 5,
        imagem: "./img/produtos/blusa-verde.png",
    },
    {
        id: "004",
        item: "Blusão Rosa",
        price: 100.00,
        qtd: 5,
        imagem: "./img/produtos/blusao-rosa.png",
    },
    {
        id: "005",
        item: "Blusão Verde",
        price: 100.00,
        qtd: 5,
        imagem: "./img/produtos/blusao-verde.png",
    },
    {
        id: "006",
        item: "Black Hoddie - verde",
        price: 150.00,
        qtd: 5,
        imagem: "./img/produtos/Black_Hood2ie_Mockup.png",
    },
    {
        id: "007",
        item: "Black Hoddie - rosa",
        price: 150.00,
        qtd: 5,
        imagem: "./img/produtos/Black_Hoodie_Mockup.png",
    },
    {
        id: "008",
        item: "Blusa exclusiva Cris",
        price: 70.00,
        qtd: 5,
        imagem: "./img/produtos/exclusivo.colorido.cris.png",
    },
    {
        id: "009",
        item: "Blusa exclusiva Mari Moura",
        price: 70.00,
        qtd: 5,
        imagem: "./img/produtos/exclusivo.colorido.mari.png",
    },
    {
        id: "0010",
        item: "Blusa exclusiva Fabiola",
        price: 70.00,
        qtd: 5,
        imagem: "./img/produtos/exclusivo.colorido.fabiola.png",
    },
    {
        id: "0011",
        item: "Exclusivo Cris Street",
        price: 70.00,
        qtd: 5,
        imagem: "./img/produtos/exclusivo-cris.png",
    },
    {
        id: "0012",
        item: "Exclusivo Mari Moura Street",
        price: 70.00,
        qtd: 5,
        imagem: "./img/produtos/exclusivo-mari.png",
    },
    {
        id: "0013",
        item: "Let´s Roll",
        price: 70.00,
        qtd: 5,
        imagem: "./img/produtos/exclusivo-patins.png",
    },
]